name: Continuous Integration 
on: 
  push:
    paths-ignore:
      - 'documentation/**'
      - 'README.md'
  pull_request:
    branches:    
      - main

jobs: 
  build: 
    name: Build and test 
    env:
      TRELLO_KEY: ${{ secrets.TRELLO_KEY }}
      TRELLO_TOKEN: ${{ secrets.TRELLO_TOKEN }}

    runs-on: ubuntu-latest 
    steps: 
    - uses: actions/checkout@v2 
    - run: docker build --target test --tag my-test-image .
    - run: docker run my-test-image todo_app/tests
    - run: docker run -e TRELLO_API_KEY="$TRELLO_KEY" -e TRELLO_API_TOKEN="$TRELLO_TOKEN" my-test-image todo_app/tests_e2e
  
  docker:
      name: Build and push
      env:
        DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
      needs: build
      runs-on: ubuntu-latest
      steps:
      - run: echo "Publishing"
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run: docker build --target production --tag $DOCKER_USER/my-todo-app:prod .
      - run: docker push $DOCKER_USER/my-todo-app:prod
      - run: docker logout




